services:
  design-system:
    container_name: design-system
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/workspace/design-system
    ports:
      - 3000:3000
      - 6006:6006
    environment:
      TZ: Asia/Tokyo
      NEXTAUTH_SECRET: +9nwmDp9RMgfyxY6wSb0Kc8QZvAjrXCLc2eSK/LDo/k=
      GITHUB_ID: Iv23lizINLA7DH6D9RtR
      GITHUB_SECRET: e35d44ff00b99658fb53dd754d027663e7d6743b
